### ISSUE TITLE
Library is not installing correctly

### ISSUE THREAD

**Issue by bogdandevlpr** [amareque/react-native-simple-accordion#1]
I've tried to install the library by: npm install react-native-simple-accordion
But the library is not found.

**Comment by amareque** [comment]
Hey! Thanks for pointing that out. 

I'll look into it and see what can be done.
I'll share some updates once I can determine what happened, hopefully with this fixed :) 

Thanks again and talk to you soon!

**Comment by amareque** [comment]
@bogdandevlpr I've updated the package. It should be working now.

I will close this issue since I've tested the example app with the latest version and it works fine. 
Thanks again for letting me know something was off with the library. Hope you can use it correctly now.
Feel free to reopen this issue if the problem persists.

Have a good one :)
